# Generated by Django 5.2.7 on 2025-11-12 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('category', models.CharField(choices=[('meeting', 'Reunião'), ('payment', 'Pagamento'), ('other', 'Outro')], max_length=50, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date'],
            },
        ),
    ]
