# Generated by Django 5.2.7 on 2025-11-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
