# Generated by Django 5.2.7 on 2025-11-05 01:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'txt'])], verbose_name='Nome do template')),
                ('placeholders', models.JSONField(default=list, verbose_name='Lista de placeholders do template')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
