# Generated by Django 5.2.7 on 2025-11-06 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='placeholders',
        ),
        migrations.RemoveField(
            model_name='template',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(upload_to='templates_app/templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'txt'])], verbose_name='Nome do template'),
        ),
    ]
