# Generated by Django 5.2.7 on 2025-11-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_remove_template_placeholders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='placeholders',
            field=models.JSONField(blank=True, default=list, verbose_name='Lista de placeholders do template'),
        ),
    ]
