# Generated by Django 5.2.7 on 2025-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_template_placeholders'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='file_content',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
